FROM quay.io/pypa/manylinux_2_28
RUN dnf install -y ninja-build wayland-devel mesa-libgbm-devel libxkbcommon-devel libunwind-devel pulseaudio-libs-devel
ENV YUNIBUILD_LOCAL_TYPE=Linux
ENV YUNIBUILD_LOCAL_VARIANT=Glibc
