FROM ubuntu:rolling
RUN apt update && apt upgrade -y && apt install -y gcc clang cmake ninja-build pkg-config libegl-dev libpulse-dev libunwind-dev libdrm-dev libgbm-dev libxext-dev libwayland-dev libwayland-egl-backend-dev libxkbcommon-dev build-essential libgles-dev
ENV YUNIBUILD_LOCAL_TYPE=Linux
ENV YUNIBUILD_LOCAL_VARIANT=Ubuntu
