# escape=`
FROM @BASEIMAGE@ as before-python
SHELL ["cmd", "/S", "/C"]

# Extract Python3
ADD https://www.python.org/ftp/python/3.12.3/python-3.12.3-embed-amd64.zip /
RUN powershell Expand-Archive -Path c:\python-3.12.3-embed-amd64.zip -DestinationPath c:\python3

FROM @BASEIMAGE@
COPY --from=before-python /python3 /python3

# Setup VS17
ADD https://aka.ms/vs/17/release/vs_buildtools.exe /
RUN (start /w vs_buildtools.exe --quiet --wait --norestart --nocache `
     --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools" `
     --add Microsoft.VisualStudio.Workload.UniversalBuildTools `
     --add Microsoft.VisualStudio.Component.Windows11SDK.22621 `
     --add Microsoft.VisualStudio.Workload.VCTools `
     --add Microsoft.Component.VC.Runtime.UCRTSDK `
     --add Microsoft.VisualStudio.Component.VC.ASAN `
     --add Microsoft.VisualStudio.Component.VC.CMake.Project `
     || IF "%ERRORLEVEL%"=="3010" EXIT 0) 

# Setup NuGet for PowerShell and VSSetup module
COPY install-vssetup.ps1 .
RUN powershell -File install-vssetup.ps1
RUN del install-vssetup.ps1

# This image needs to be tagged as yunibuild-msvc17-new
