FROM alpine:edge
RUN apk update && apk add g++ clang cmake python3 ninja-is-really-ninja wayland-dev pulseaudio-dev libxkbcommon-dev libunwind-dev mesa-dev
ENV YUNIBUILD_LOCAL_TYPE=Linux
ENV YUNIBUILD_LOCAL_VARIANT=Alpine
